# Generated by Django 3.2.16 on 2023-03-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="services.plan",
                verbose_name="Тарифный план",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="services.service",
                verbose_name="Сервис",
            ),
        ),
    ]
