# Generated by Django 3.2.16 on 2023-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_auto_20230328_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена"),
        ),
    ]
