# Generated by Django 3.2.16 on 2023-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_subscription_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="comment",
            field=models.CharField(
                default="", max_length=255, verbose_name="Комментарий"
            ),
            preserve_default=False,
        ),
    ]
